apiVersion: v2
name: affine-cloud
description: A Helm chart for AFFiNE Cloud

type: application
version: 0.6.1
appVersion: '0.6.1'

dependencies:
  - name: postgresql
    version: 13.2.23
    repository: https://charts.bitnami.com/bitnami
