ingress:
  enabled: false
  className: ''
  annotations:
    kubernetes.io/ingress.class: nginx
  host: affine.pro
  tls: []

graphql:
  service:
    type: ClusterIP
    port: 3000

web:
  service:
    type: ClusterIP
    port: 8080
