[package]
name = "affine_server_native"
version = "1.0.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
chrono = "0.4"
file-format = { version = "0.25", features = ["reader"] }
napi = { version = "2", default-features = false, features = [
  "napi6",
  "async",
] }
napi-derive = { version = "2", features = ["type-def"] }
rand = "0.8"
sha3 = "0.10"
tiktoken-rs = "0.5.9"
y-octo = { git = "https://github.com/y-crdt/y-octo.git", branch = "main" }

[target.'cfg(not(target_os = "linux"))'.dependencies]
mimalloc = { workspace = true }

[target.'cfg(all(target_os = "linux", not(target_arch = "arm")))'.dependencies]
mimalloc = { workspace = true, features = ["local_dynamic_tls"] }

[dev-dependencies]
tokio = "1"

[build-dependencies]
napi-build = "2"
