name: standard check

on:
    push:
        branches: [master]
    pull_request:
        branches: [master]

jobs:
    main:
        name: Nx Cloud - Main Job
        uses: nrwl/ci/.github/workflows/nx-cloud-main.yml@v0.6
        secrets: inherit
        with:
            main-branch-name: master
            number-of-agents: 3
            parallel-commands: |
                pnpm exec nx-cloud record -- pnpm exec nx format:check
            parallel-commands-on-agents: |
                pnpm exec nx affected --target=lint --parallel=3 --exclude=components-common,keck,theme
                pnpm exec nx affected --target=build --parallel=3

    agents:
        name: Nx Cloud - Agents
        uses: nrwl/ci/.github/workflows/nx-cloud-agents.yml@v0.6
        secrets: inherit
        with:
            number-of-agents: 3
