{{- if .Values.app.oauth.google.enabled -}}
apiVersion: v1
kind: Secret
metadata:
  name: "{{ .Values.app.oauth.google.secretName }}"
type: Opaque
data:
{{- ( include "objectStorage.oauth.google" . ) | indent 2 -}}

{{- end }}
