{{- if .Values.app.oauth.github.enabled -}}
apiVersion: v1
kind: Secret
metadata:
  name: "{{ .Values.app.oauth.github.secretName }}"
type: Opaque
data:
{{- ( include "objectStorage.oauth.github" . ) | indent 2 -}}

{{- end }}
