{{- if .Values.app.objectStorage.r2.enabled -}}
apiVersion: v1
kind: Secret
metadata:
  name: "{{ .Values.app.objectStorage.r2.secretName }}"
type: Opaque
data:
  {{- ( include "objectStorage.r2" . ) | indent 2 -}}
{{- end }}
